# Site settings
title: Shekhar Gupta
description: 'Mobile Applicaiton Developer'
url: ''
baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Shekhar Gupta'
  email: theshekhargupta@gmail.com
  twitter_username: iamshekhargupta
  facebook_username: theshekhargupta
  github_username:  theshekhargupta
  linkedin_username:  guptashekhar

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
